FROM registry1.dso.mil/ironbank/opensource/nodejs/debian/nodejs:20.6.1 as build

WORKDIR /llm-frontend
COPY --chown=node:0 . /llm-frontend
RUN npm install ci --legacy-peer-deps
RUN npm run build \
 && mv /llm-frontend/public/ /llm-frontend/dist/public/

FROM registry1.dso.mil/ironbank/opensource/nodejs/debian/nodejs:20.6.1

RUN npm install --global serve
COPY --from=build --chown=node:0 /llm-frontend/dist /dist
