FROM registry1.dso.mil/ironbank/opensource/nodejs/debian/nodejs:18.18.0 as build

WORKDIR /llm-frontend
COPY --chown=node:node . /llm-frontend
RUN npm install --legacy-peer-deps
RUN npm run build \
 && mv /llm-frontend/public/ /llm-frontend/dist/public/


FROM registry1.dso.mil/ironbank/opensource/nginx/nginx:1.25.2-distroless

COPY --from=build /llm-frontend/dist /usr/share/nginx/html
COPY ../infra/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
ENTRYPOINT ["nginx", "-g", "daemon off;"]
