FROM registry1.dso.mil/ironbank/opensource/nodejs/debian/nodejs:20.6.1 as build

WORKDIR /llm-frontend
COPY --chown=node:0 . /llm-frontend
RUN npm install ci --legacy-peer-deps && npm run build

ENTRYPOINT ["npx", "vite", "serve", "--port", "3000"]