version: '3'

services:
  mock-f5:
    container_name: mock-f5
    image: haproxy:2.8
    ports:
      - "80:80"
    volumes:
      - ./mock-f5/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./mock-f5/cors.lua:/usr/local/etc/haproxy/cors.lua
    networks:
      - host

  frontend-proxy:
    container_name: frontend-proxy
    image: haproxy:2.8
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/cors.lua:/usr/local/etc/haproxy/cors.lua
    networks:
      - host

  frontend:
    container_name: frontend
    image: llm-frontend:1.0.0-alpha
    build:
      context: ../
      dockerfile: Dockerfile.production
    networks:
      - host

  frontend-cadvisor:
    container_name: frontend-cadvisor
    image: registry1.dso.mil/ironbank/opensource/google/cadvisor:0.45.0
    ports:
      - 9090:9090
    command: --port=9090
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - ~/.local/share/docker:/var/lib/docker:ro
    networks:
      - host

networks:
  host:
