version: "3"

services:
  frontend-proxy:
    container_name: frontend-proxy
    image: haproxy:2.8
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/cors.lua:/usr/local/etc/haproxy/cors.lua
    networks:
      - host

  frontend:
    container_name: frontend
    image: gaia/frontend:1.0.0-alpha
    build:
      context: ../
      dockerfile: Dockerfile.production
    networks:
      - host

networks:
  host:
