version: "3"

services:
  frontend-proxy:
    container_name: frontend-proxy
    image: gaia/haproxy24:v2.4.22
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - host

  frontend:
    container_name: frontend
    image: gaia/frontend:1.1.0
    restart: unless-stopped
    networks:
      - host

networks:
  host:
