version: '3'
services:
  frontend-proxy:
    container_name: frontend-proxy
    image: haproxy:2.8
    # image: registry1.dso.mil/ironbank/opensource/haproxy/haproxy22:v2.2.31 # harden
    ports:
      - "80:80"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: Dockerfile

  frontend-cadvisor:
    container_name: frontend-cadvisor
    image: google/cadvisor:latest
    command: --port=9090
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
